version: '3'

services:
    app:
        container_name: "application"
        build:
            context: ../
            dockerfile: deployments/app/Dockerfile
        ports:
            - "5000:5000"

